Muchos cambios en lang
allnnde/pf2e-esp-translation pull request #35
Opened 2023-10-08 22:36 UTC by HonzoNebro

2023-10-09 10:07 UTC, allnnde requested changes

2023-10-09 10:07 UTC, allnnde commented on trad/en/action-en.json
Este archivo no debe cambiar, ya que es el original de ingles desde donde se tomo la ultima traduccion

2023-10-12 10:21 UTC, merged

2023-10-12 10:22 UTC, allnnde commented
ahi le hago rolback al archvo en la carpeta "en" asi queda ok

2023-10-16 18:01 UTC, HonzoNebro commented on trad/en/action-en.json
Uy, hice el cambio a lo bestia para ir más rápido, no pretendía subir esto jaja

2023-10-16 18:04 UTC, allnnde commented on trad/en/action-en.json
cero drama, ya esta corregido e integrado!! gracias por el trabajo!